### ISSUE TITLE
Click on checkbox selects wrong subtask

### ISSUE THREAD

**Issue by MontrealSergiy** [aces/cbrain#872] opened 2019-09-27 15:56 UTC
In the task list, a click on a subtask sometimes selects a subtask above it.
to reproduce

1. Login as admin.
2. Go to the task page
3. Filter in 'spark' tasks
4. Open several hierarchical tasks
5. Click on very bottom subtask (actually any subtask of the bottom hierarchical task)
Observed: a different subtask is selected
Expected: the UX should select the task the user clicked on.

[task_selection.mp4.zip](https://github.com/aces/cbrain/files/3663554/task_selection.mp4.zip)

**Comment by MontrealSergiy** [comment] 2019-09-27 15:57
Video attached

**Comment by natacha-beck** [comment] 2019-11-06 18:37
I was not able to reproduce this one. Even when I followed the exact same step.

**Comment by MontrealSergiy** [comment] 2019-11-06 19:31
Ir-reproducible then

**Comment by prioux** [comment] 2019-11-07 19:52
I was not able to reproduce it either, so I'll close it. Let's just keep it in mind. If it happens again Sergiy (or anyone else), keep your tab open so we can inspect the element's IDs !

**Closed by prioux** 2019-11-07 19:52 UTC
Labels: Bug, Priority: Low, User Interface
