### ISSUE TITLE
In tool selection panel, search field overlaps tool list

### ISSUE THREAD

**Issue by glatard** [aces/cbrain#540] opened 2016-11-02 15:27 UTC
See attached screenshot. 
![screenshot from 2016-11-02 11-26-02](https://cloud.githubusercontent.com/assets/5174953/19935103/4ab11882-a0ef-11e6-8cc6-53830978ed64.png)

**Comment by crocodoyle** [comment] 2016-11-02 15:29
This will be addressed in the Bootstrapification

**Comment by natacha-beck** [comment] 2019-11-22 17:47
I was not able to reproduce it.

**Comment by natacha-beck** [comment] 2020-01-06 20:18
To reproduce, we need to unzoom. 
![bug_tools](https://user-images.githubusercontent.com/777590/71846105-c9ad6380-3097-11ea-94eb-85c291222e75.png)

**Comment by natacha-beck** [comment] 2020-01-17 19:42
I already explore this one and I get a not really good solution. It is not easy to work with. 
It is due to the hard-coded value of 170px here https://github.com/aces/cbrain/blob/36b99ebbd2b717d1a36cc4e027602b43080b0f64/BrainPortal/app/assets/stylesheets/userfiles.css.erb#L121 and here https://github.com/aces/cbrain/blob/36b99ebbd2b717d1a36cc4e027602b43080b0f64/BrainPortal/app/assets/stylesheets/userfiles.css.erb#L126 
But removing it will not be the solution it helps a little bit but does not work well. The `Select Tool` panel have a really complicated structure with some imbricated elements. Since the UI will be changed in the future it may be not useful to spend more time on this.

**Comment by prioux** [comment] 2020-01-17 19:55
The float is the problem. Just adjust the layout of the panel so no 'float' is used.

**Comment by natacha-beck** [comment] 2020-02-10 20:39
Fix in #915

**Closed** 2020-02-10 20:38 UTC
Labels: Bug
