### ISSUE TITLE
Number of files selected on Files page shows 1 more files than is selected

### ISSUE THREAD

**Issue by shots47s** [aces/cbrain#685] opened 2018-01-16 14:38 UTC
On the Files tab, it appears that always 1 file is thought to be selected, so that when none are, it shows that 1 is, and it is always 1+ the number of files selected.  Turns out that it is not local to the page and that I had a file selected in another project, which seems like it should not be.  When I went to the other project and deselected the file, then it updated properly.  

![image](https://user-images.githubusercontent.com/9719/34994127-87fe92e4-faa0-11e7-82fe-12157d6741d0.png)

**Comment by prioux** [comment] 2018-01-16 16:31
Well, it was designed like that so that people can select files in a project, switch project, select more files, switch project etc, and then apply an operation to all the files. That is why the counter at the top indicates how many files are selected in total.

Granted, it could be a bit confusing, and the alternative is this: whenever a user switches project, the selected files are reset. If a user wants to select files from multiple projects, they have to use the 'all' project (which in fact means no project filtering). Comments?

**Comment by gkiar** [comment] 2018-01-16 16:32
This is a discussion that @crocodoyle @prioux and I had on Slack a few weeks ago - we came to the conclusion that the option @prioux suggests in his second paragraph above would be the best path forward, I believe.

**Comment by prioux** [comment] 2018-01-16 16:37
Well, I'm awaiting your pull requests.

**Comment by prioux** [comment] 2018-02-01 23:02
Duplicate of #671

**Comment by prioux** [comment] 2018-02-19 17:06
Closed by #706

**Closed by prioux** 2018-02-19 17:06 UTC
Labels: Bug, Priority: High
