### ISSUE TITLE
In files table, tag filtering doesn't show properly.

### ISSUE THREAD

**Issue by glatard** [aces/cbrain#207] opened 2015-09-10 14:02 UTC
![screenshot from 2015-09-10 10 00 59](https://cloud.githubusercontent.com/assets/5174953/9790292/37a9f826-57a3-11e5-827c-2d5436b08f4c.png)

**Comment by remibernard** [comment] 2015-09-10 14:39
Duplicate of issue #201. The corresponding fix, commit ca536817461c9e902ecb113105a17df45da656f2, is awaiting merge in pull request #200 .

**Comment by prioux** [comment] 2015-09-10 19:58
Acknowledged.

**Closed by prioux** 2015-09-10 19:58 UTC
Labels: Bug
