### ISSUE TITLE
Uploading a file with no file selected: no error message, progress bar shows 1K of info uploaded anyway

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#326] opened 2016-02-04 20:14 UTC
(New dev interface only)

Weird behavior when uploading no file at all (e.g. clicking upload without having selected a file):

* no error message
* progress bar appears

**Comment by prioux** [comment] 2016-02-04 20:30
This also triggers an internal error that can't be logged because at the moment of recording it in our ExceptionLog table, we raise an exception:

<pre>
ActiveRecord::StatementInvalid (Mysql2::Error: Got a packet bigger than 'max_allowed_packet' bytes: INSERT INTO `exception_logs`
...
(I spare you the 1mb big dump I saw here)
</pre>

I'm assuming this is directly related to expanding the content of @base_scope while trying to log information about the original exception.

**Comment by prioux** [comment] 2016-02-05 00:20
The reason it's not inserted into the exception log is that it's trying to log the SQL statement, which not only made the SQL request fail, but also is too big to fit in the exception log.

The SQL statement was something like:

<pre>
select * from SyncStatus where userfile_id in ( 1,2,3 ... all userfile IDs !!! )
</pre>

(no other where clause... the order of the userfile IDs seem to match the order of the full list of accessible userfile in the current scope)

**Comment by prioux** [comment] 2016-02-05 00:58
I found out the big SQL statement (and several others) are not triggered by the initial POST to upload the file (which renders properly and return to the browser the index page), but by TWO (2) ajax queries that follows immediately.

<pre>
(end of initial POST request here)
Completed 303 See Other in 224.2ms (ActiveRecord: 55.8ms)


Started GET "/userfiles" for 127.0.0.1 at 2016-02-04 19:29:22 -0500
Processing by UserfilesController#index as */*
(huge amount of SQL queries here)
Completed 200 OK in 82669.5ms (Views: 77852.6ms | ActiveRecord: 4611.7ms)


Started GET "/userfiles?_=1454632245881" for 127.0.0.1 at 2016-02-04 19:30:45 -0500
Processing by UserfilesController#index as JS
(more queries, but less than previous request)
Completed 200 OK in 1482.1ms (Views: 893.5ms | ActiveRecord: 393.9ms)
<pre>

**Comment by remibernard** [comment] 2016-02-05 07:04
As far as I can see there are two issues in play:
- The upload dialog's UI should disable the download button when the file selection is empty. This solves the immediate problem right away and does not incur any design changes (this is the reported bug).
- The controller's `create` action forces a redirect ([`userfiles_controller.rb:402`](https://github.com/aces/cbrain/blob/524f7612ea076260eb81f1eaa7f329aa57ae884a/BrainPortal/app/controllers/userfiles_controller.rb#L402)) when the provided file is empty. This behavior is a leftover from the previous interface, but is still required in case the client's browser does not support AJAX uploads. The issue is that the redirect must be kept, yet must be avoided for AJAX uploads. Ideally, the AJAX request could be made using JSON, but sending files over JSON with the DOM API would be messy. Albeit clunky, the simplest solution would be to respond with just `head :unprocessable_entity` to AJAX requests.

One possible reason for why the SQL statement got so large is that the redirect was marked as an AJAX request, which disabled all pagination (and thus requested everything).

**Closed** 2016-02-05 21:26 UTC
Labels: Bug, High Priority
